#!/usr/bin/env bash
#commands to install nginx server

apt-get update
apt-get install nginx
ufw 'Nginx HTTP'

#create index.html with Hello World! inside
echo "Hello World!" | tee index.html

#test nginx configurations
nginx -t

#Restart and reload
service nginx reload
