#!/usr/bin/env bash
#commands to install nginx server

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'

#create index.html with Hello World! inside
echo "Hello World!" | tee /var/www/html/index.html

#test nginx configurations
nginx -t

#Start nginx
service nginx start

