#!/usr/bin/env bash
#Configure your Nginx server so that /redirect_me is redirecting to another page.

apt-get update
apt-get install -y nginx

#create index.html with Hello World! inside
echo "Hello World!" | sudo tee /var/www/html/index.html

replace_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;\n"

sed -i "s/server_name _;/$replace_string/" /etc/nginx/sites-enabled/default

#Create the 404.html error page
echo "Ceci n'est pas une page" | tee /var/www/html/404.html

#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
replace_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sed -i "s/listen 80 default_server;/$replace_string/" /etc/nginx/sites-enabled/default

#test nginx configurations
nginx -t

#Restart nginx
service nginx restart
