#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

sudo apt-get update -y
sudo apt-get install haproxy -y

# edit config file
cfg_server=\
"
frontend load_balancer
        bind *:80
        mode http
        default_backend web_servers
backend web_servers
        balance roundrobin
        server 334384-web-01 100.26.132.172:80 check
        server 334384-web-02 100.25.132.101:80 check
"

sudo echo "$cfg_server" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
sudo sed -i "8 a\ENABLED=1\n" /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy start
