#!/usr/bin/env bash
# Run nginx as nginx user

# kill apache2 server
sudo pkill -f apache2

# change permissions on config file
sudo chmod 644 /etc/nginx/nginx.conf

# set the value of user in the config file to nginx 
sudo sed -i "s/user www-data/user nginx/" /etc/nginx/nginx.conf

# update listening ports to 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default

# restart nginx
sudo -u nginx service nginx start
