#!/usr/bin/env bash
# ssh_config - connect to a server without typing a password.

Host *
    PasswordAuthentication no
    IdentityFile ~/.ssh/school
    SendEnv LANG LC_*
    HashKnownHosts yes
    GSSAPIAuthentication yes
    HostName 3.86.18.187
    User ubuntu
